use crate::business::domain::user::User;

pub struct UserService;

impl UserService {
    pub fn list_users() -> Vec<User> {
        vec![
            User { id: 1, name: "example".into(), email: "example@email.com".into() }
        ]
    }

    pub fn create_user(name: String, email: String) -> User {
        // In real app, ID should be generated by DB
        User {
            id: rand::random::<u32>(),
            name,
            email,
        }
    }
}
